# Generated by Django 5.0.14 on 2026-08-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_lessonprogress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonprogress',
            options={},
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
