# Generated by Django 5.0.14 on 2026-08-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_studentfee_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
